version: '3.8'

services:
  warehouse-main:
    image: warehouse-main:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-javaagent:/app/jmx_prometheus_javaagent.jar=12345:/app/jmx_exporter_config.yml
    volumes:
      - ./jmx_exporter_config.yml:/app/jmx_exporter_config.yml
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  prometheus_data: