package ru.demo.wms.view;

import java.awt.Color;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.view.document.AbstractPdfView;

import ru.demo.wms.model.ShipmentType;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.HeaderFooter;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

public class ShipmentTypePdfView extends AbstractPdfView {
	
	protected void buildPdfMetadata(Map<String, Object> model, Document document, HttpServletRequest request) {
		//to add header, 2nd param must be false, true means generates number
		HeaderFooter header = new HeaderFooter(new Phrase("SHIPMENTTYPE PDF VIEW"),false);
		header.setAlignment(Element.ALIGN_CENTER);
		//add to document as header
		document.setHeader(header);
		
		//to add header, 2nd can be null/data(display after number) or true 
		HeaderFooter footer = new HeaderFooter(new Phrase("GENERATED BY NIT - Page#"),null);
		footer.setAlignment(Element.ALIGN_RIGHT);
		//add to document as footer
		document.setFooter(footer);
	}

	protected void buildPdfDocument(
			Map<String, Object> model, 
			Document document, 
			PdfWriter writer,
			HttpServletRequest request, 
			HttpServletResponse response)
					throws Exception 
	{
	

		//Image img = Image.getInstance("https://www.pochta.ru/static/images/logo-light.3c5f75f9dc91.svg");
		Image img = Image.getInstance("https://www.pochta.ru/static/images/logo-light.3c5f75f9dc91.svg");
		//set width and height
		img.scaleAbsolute(250, 40);
		//set alignment
		img.setAlignment(Element.ALIGN_CENTER);
		//add to document
		document.add(img);
		
		//file download
		response.addHeader("Content-Disposition", "attachment;filename=ShipmentType.pdf");
		
		//font familiy, size, style, color
		Font titleFont = new Font(Font.TIMES_ROMAN,22,Font.BOLD,Color.BLUE);
		
		// paragraph -- text and font
		Paragraph p = new Paragraph("SHIPMENT TYPE PDF DATA",titleFont);
		
		//alignment , left/center/right
		p.setAlignment(Element.ALIGN_CENTER);
		
		//give space between paragraph and next element(table)
		p.setSpacingAfter(10.0f);
		
		//add paragraph to document
		document.add(p);
		
		//reading data from controller
		@SuppressWarnings("unchecked")
		List<ShipmentType> list =  (List<ShipmentType>) model.get("list");
		
		
		//font for table heading
		Font tableFont = new Font(Font.TIMES_ROMAN,12,Font.BOLD,new Color(51, 153, 102));
		
		//creating table with no.of column(not rows)
		PdfPTable table = new PdfPTable(6); // 1 row = 6 columns
		table.addCell(new Phrase("ID",tableFont));
		table.addCell(new Phrase("MODE",tableFont));
		table.addCell(new Phrase("CODE",tableFont));
		table.addCell(new Phrase("ENABLE",tableFont));
		table.addCell(new Phrase("GRADE",tableFont));
		table.addCell(new Phrase("NOTE",tableFont));
		
		//add list data given by Controller
		for(ShipmentType st:list) {
			//convert non-String data(int,double..) to String type.
			table.addCell(String.valueOf(st.getId()));
			table.addCell(st.getShipMode());
			table.addCell(st.getShipCode());
			table.addCell(st.getEnbleShip());
			table.addCell(st.getShipGrade());
			table.addCell(st.getShipDesc());
		}
		
		//add table to document  
		document.add(table);
		
	}

}
/*
Класс ShipmentTypePdfView расширяет AbstractPdfView для создания PDF-отчета о типах отправлений (ShipmentType). Этот вид позволяет генерировать документы PDF, содержащие подробные данные о каждом типе отправления, что может быть полезно для анализа, отчетности или документации. Вот как работает этот класс:

Основные методы:
buildPdfMetadata:
Устанавливает метаданные для PDF-документа, включая заголовок и нижний колонтитул. Заголовок содержит фразу "SHIPMENTTYPE PDF VIEW", а нижний колонтитул включает метку времени генерации и номер страницы.

buildPdfDocument:
Отвечает за построение содержимого PDF-документа. Этот метод считывает данные о типах отправлений из модели, переданной контроллером, и использует их для формирования таблицы в документе. Также метод добавляет изображение-логотип на верх документа, заголовок документа и таблицу с данными.

Шаги генерации содержимого:
Добавление изображения:
В документ вставляется изображение, которое может служить логотипом компании или другой важной визуальной информацией. Размер и выравнивание изображения настраиваются.

Настройка заголовка:
Добавляется заголовок с настраиваемым шрифтом и цветом, выравнивается по центру и отделяется от остального текста пространством.

Создание и заполнение таблицы:
Формируется таблица для отображения данных о типах отправлений. Каждый столбец таблицы соответствует определенному атрибуту объекта ShipmentType, такому как ID, режим отправления, код, статус активации, оценка качества и описание. Для заголовков столбцов применяется специальное оформление.

Формирование отчета:
Все данные о типах отправлений переносятся в таблицу, где каждая запись занимает отдельную строку.

Настройка ответа:
Устанавливается заголовок ответа Content-Disposition, чтобы браузер предлагал скачать файл вместо отображения его содержимого.
Рекомендации и замечания:
Безопасность данных: При генерации отчетов убедитесь, что конфиденциальная информация защищена и доступна только авторизованным пользователям.

Пользовательское оформление: Рассмотрите возможность дополнительной настройки стилей элементов PDF для улучшения визуального восприятия документа. Можно изменить шрифты, цвета и форматирование таблиц для лучшей читабельности.

Производительность: Создание сложных PDF-документов может быть ресурсоемким процессом. Для больших объемов данных следует учитывать влияние на производительность и, при необходимости, оптимизировать процесс.

ShipmentTypePdfView представляет собой мощный инструмент для создания профессиональных PDF-отчетов в Spring-приложениях, позволяя эффективно представлять и делиться важной информацией.
*/